[project]
name = "justkeepswimming"
<<<<<<< HEAD
version = "0.0.0"
=======
version = "0.1.0"
>>>>>>> f83e5e1 (fix: set project as prerelease)
description = "A small game about a fish in the deep sea."

readme = "README.md"
license = "GPL-3.0"

requires-python = ">=3.13"
dependencies = [
    "asyncio>=4.0.0",
    "psutil>=7.2.2",
    "pygame-ce>=2.5.6",
    "rich>=14.3.1",
]

[tool.uv.sources]
nuitka = { git = "https://github.com/Nuitka/Nuitka" }

[dependency-groups]
bump = [
    "python-semantic-release>=10.5.3"
]

build = [
    "imageio>=2.37.2",
    "nuitka",
    "toml>=0.10.2",
]
dev = [
    "matplotlib>=3.10.8",
    "autopep8>=2.3.2",
    "black>=26.1.0",
    "flake8>=7.3.0",
    "isort>=7.0.0",
    "mypy>=1.19.1",
    "pre-commit>=4.5.1",
    "pycodestyle>=2.14.0",
    "pylint>=4.0.4",
    "types-psutil>=7.2.1.20260116",
    "types-toml>=0.10.8.20240310",
]

[project.scripts]
play = "justkeepswimming.main:main"
build = "justkeepswimming.build:main"
profiler-generate-summary = "justkeepswimming.debug.viewer:cli_summary"
profiler-generate-frame-summary = "justkeepswimming.debug.viewer:cli_frame"

[tool.nuitka]
standalone = true
enable-plugin = ["pygame"]

[build-system]
requires = ["setuptools>=65.5.1", "wheel"]
build-backend = "setuptools.build_meta"

[tool.semantic_release]
assets = []
build_command_env = []
commit_message = "chore: bump version to v{version}\n\nAutomatically generated by CI/CD."
commit_parser = "conventional"
logging_use_named_masks = false
major_on_zero = true
allow_zero_version = true
no_git_verify = false
tag_format = "v{version}"
add_partial_tags = false

[tool.semantic_release.branches.main]
match = "main"
prerelease_token = "rc"
prerelease = false

[tool.semantic_release.changelog]
mode = "update"
insertion_flag = "<!-- version list -->"
template_dir = "templates"

[tool.semantic_release.changelog.default_templates]
changelog_file = "CHANGELOG.md"
output_format = "md"
mask_initial_release = true

[tool.semantic_release.changelog.environment]
block_start_string = "{%"
block_end_string = "%}"
variable_start_string = "{{"
variable_end_string = "}}"
comment_start_string = "{#"
comment_end_string = "#}"
trim_blocks = false
lstrip_blocks = false
newline_sequence = "\n"
keep_trailing_newline = false
extensions = []
autoescape = false

[tool.semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "semantic-release <semantic-release>"

[tool.semantic_release.commit_parser_options]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
other_allowed_tags = ["build", "chore", "ci", "docs", "style", "refactor", "test"]
allowed_tags = ["feat", "fix", "perf", "build", "chore", "ci", "docs", "style", "refactor", "test"]
default_bump_level = 0
parse_squash_commits = true
ignore_merge_commits = true

[tool.semantic_release.remote]
name = "origin"
type = "github"
ignore_token_for_push = false
insecure = false

[tool.semantic_release.publish]
upload_to_vcs_release = false

